# Generated by Django 4.2.3 on 2023-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
