# Generated by Django 4.2.3 on 2023-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_qrcode_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="eventSHORTDESC",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
