# Generated by Django 4.2.3 on 2023-07-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_cart_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketpurchase",
            name="stripe_session_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
