# Generated by Django 4.2.3 on 2023-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_eventshortdesc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="eventDISCRIPTION",
            field=models.TextField(null=True),
        ),
    ]
