# Generated by Django 4.2.3 on 2023-07-29 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_ticketpurchase_stripe_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="eventLAN",
        ),
        migrations.RemoveField(
            model_name="event",
            name="eventLON",
        ),
    ]
